transflow:
  inputs:
    - plugin-id: plugin-kafka-input
      config:
        bootstrap-servers: "localhost:9092"
        topic: "test"
      filters:
        - plugin-id: plugin-json-filter
      outputs:
        - plugin-id: plugin-stdout