package org.sunyaxing.transflow.transflowapp;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.sunyaxing.transflow.transflowapp.common.ChainManager;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@MapperScan({"org.sunyaxing.transflow.transflowapp.repositories"})
@SpringBootApplication
public class TransflowAppApplication {

    public static void main(String[] args) {
        SpringApplication.run(TransflowAppApplication.class, args);
        ChainManager.start();
    }

}
